# Generated by Django 4.2.1 on 2023-05-13 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('name', models.TextField(max_length=200, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=200, null=True)),
                ('telephone', models.CharField(max_length=200, null=True)),
                ('city', models.CharField(max_length=200, null=True)),
                ('address', models.CharField(max_length=200, null=True)),
                ('activity_type', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SearchLeads',
            fields=[
                ('search_date', models.DateTimeField(primary_key=True, serialize=False)),
                ('list_results', models.ManyToManyField(to='dashboard.lead')),
            ],
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
