# Generated by Django 4.2.1 on 2023-05-14 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_lead_searchleads_delete_choice_delete_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=200, verbose_name='Città')),
                ('region', models.CharField(max_length=200, verbose_name='Regione')),
                ('activity_type', models.CharField(max_length=200, verbose_name='Tipo attività')),
                ('exclude_no_email', models.BooleanField(default=True, verbose_name='Escludi senza email')),
            ],
        ),
    ]
