# Generated by Django 4.2.1 on 2023-05-14 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_searchleads_slug_alter_searchleads_list_results'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchleads',
            name='finished',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='searchleads',
            name='search_options',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dashboard.searchoptions'),
        ),
    ]
