# Generated by Django 4.2.1 on 2023-05-16 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_searchoptions_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchleads',
            name='name',
            field=models.CharField(default='', max_length=200, verbose_name='Nome'),
            preserve_default=False,
        ),
    ]
