# Generated by Django 4.2.1 on 2023-05-16 12:55

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_alter_lead_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='slug',
            field=autoslug.fields.AutoSlugField(primary_key=True, serialize=False),
        ),
    ]
