# Generated by Django 4.2.1 on 2023-05-30 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_lead_star'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='contacted',
            field=models.BooleanField(default=False),
        ),
    ]
